services:
  club_app:
    build:
      dockerfile: Dockerfile
      context: .
    command: > 
      sh -c "python3 ./utils/wait_for_postgres.py && 
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"
    container_name: blog_app
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15-alpine
    container_name: blog_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vas3k_blog
    ports:
      - "5432:5432"
