services:
  blog_app:
    image: ghcr.io/rulikkk/new-blog
    command: make docker-run-production
    container_name: blog_app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - POSTGRES_DB=rulikkk_blog
      - POSTGRES_USER=rulikkk
      - POSTGRES_PASSWORD=rulikkk
      - POSTGRES_HOST=postgres
      - TELEGRAM_TOKEN  # values below come from .env
      - TELEGRAM_MAIN_CHAT_ID
      - SENTRY_DSN
      - PATREON_CLIENT_ID
      - PATREON_CLIENT_SECRET
      - CLUB_OPENID_CONFIG_SECRET
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    env_file:
      - .env
    restart: always
    volumes:
      - ./frontend/static:/tmp/static
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8022:8022"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: rulikkk
      POSTGRES_PASSWORD: rulikkk
      POSTGRES_DB: rulikkk_blog
    volumes:
      - ./pgdata_rulikkk_blog:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54324:5432"
